import { build } from "esbuild";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

async function main() {
  const result = await build({
    entryPoints: [resolve("src/shim/page-entry.ts")],
    bundle: true,
    format: "iife",
    target: "es2022",
    platform: "browser",
    write: false,
    minify: true,
    legalComments: "none",
  });
  const file = result.outputFiles[0];
  if (!file) throw new Error("esbuild produced no output");
  const src = file.text;
  const hash = createHash("sha256").update(src).digest("base64");

  const gen = `// GENERATED by scripts/bundle-shim.ts — do not edit.
export const PAGE_SHIM_SRC: string = ${JSON.stringify(src)};
export const PAGE_SHIM_HASH: string = ${JSON.stringify(hash)};
`;
  writeFileSync(resolve("src/shim-bundle.ts"), gen);
  console.log(
    `[bundle-shim] wrote src/shim-bundle.ts (${src.length} bytes, hash=${hash})`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
