name = "eth-tennis-gateway"
compatibility_date = "2026-04-23"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "*.eth.tennis/*"
zone_name = "eth.tennis"

[[routes]]
pattern = "*.*.eth.tennis/*"
zone_name = "eth.tennis"

[[routes]]
pattern = "*.*.*.eth.tennis/*"
zone_name = "eth.tennis"

[[routes]]
pattern = "*.*.*.*.eth.tennis/*"
zone_name = "eth.tennis"

[[routes]]
pattern = "*.*.*.*.*.eth.tennis/*"
zone_name = "eth.tennis"
